AppsyncSampleAuthApiStack.GraphQLAPIID = mhx2ixnrirdrzlaewplox64cii
AppsyncSampleAuthApiStack.GraphQLAPIKey = da2-dwbu7dxetfdwlc2wd3mnrc5ivy
AppsyncSampleAuthApiStack.GraphQLAPIURL = https://r4gxoi77u5clldlalhh5gcdfve.appsync-api.us-east-1.amazonaws.com/graphql
AppsyncSampleAuthApiStack.UserPoolClientId = 6vstsucijcel15ev271ll4g45t
AppsyncSampleAuthApiStack.UserPoolId = us-east-1_EXyCwfcpI